export const userData = [
    {
      name: "Jan",
      "Active User": 4000,
    },
    {
      name: "Feb",
      "Active User": 3000,
    },
    {
      name: "Mar",
      "Active User": 5000,
    },
    {
      name: "Apr",
      "Active User": 4000,
    },
    {
      name: "May",
      "Active User": 3000,
    },
    {
      name: "Jun",
      "Active User": 2000,
    },
    {
      name: "Jul",
      "Active User": 4000,
    },
    {
      name: "Agu",
      "Active User": 3000,
    },
    {
      name: "Sep",
      "Active User": 4000,
    },
    {
      name: "Oct",
      "Active User": 1000,
    },
    {
      name: "Nov",
      "Active User": 4000,
    },
    {
      name: "Dec",
      "Active User": 3000,
    },
  ];

  export const productData = [
    {
      name: "Jan",
      "Sales": 4000,
    },
    {
      name: "Feb",
      "Sales": 3000,
    },
    {
      name: "Mar",
      "Sales": 5000,
    },
  ];

  
  export const userRows = [
    { id: 1, lastName: 'Kefyalew', firstName: 'Eyob', fullname: 'Eyob Kefyalew',location: "Kebena, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '405 ETB' },
    { id: 2, lastName: 'Abelneh', firstName: 'Samuel', fullname: 'Samuel Abelneh',location: "Summit, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '55 ETB' },
    { id: 3, lastName: 'Bekele', firstName: 'Kalkidan', fullname: 'Kalkidan Bekele',location: "Saris, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '885 ETB' },
    { id: 4, lastName: 'Sirak', firstName: 'Hermela', fullname: 'Hermela Sirak',location: "Ayat, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '1255 ETB' },
    { id: 5, lastName: 'kebede', firstName: 'Abebe', fullname: 'Abebe kebede',location: "Jemo, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '245 ETB' },
    { id: 6, lastName: 'Snow', firstName: 'Jon', fullname: 'Jon Snow',location: "Mexico, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '2545 ETB' },
    { id: 7, lastName: 'Kefyalew', firstName: 'Eyob', fullname: 'Eyob Kefyalew',location: "Megenaga, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '855 ETB' },
    { id: 8, lastName: 'Samuel', firstName: 'Abelneh', fullname: 'Samuel Abelneh',location: "6Kilo, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '955 ETB' },
    { id: 9, lastName: 'Bekele', firstName: 'Kalkidan', fullname: 'Kalkidan Bekele',location: "Piasa, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '255 ETB' },
    { id: 10, lastName: 'Hermela', firstName: 'Sirak', fullname: 'Hermela Sirak',location: "4Kilo, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '255 ETB' },
    { id: 11, lastName: 'Kebede', firstName: 'Abebe', fullname: 'Abebe Kebede',location: "Gerji, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '455 ETB' },
    { id: 12, lastName: 'Jon', firstName: 'Snow', fullname: 'Snow Jon',location: "Goro, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '265 ETB' },
    { id: 13, lastName: 'Abdurahman', firstName: 'Sammy', fullname: 'Sammy Abdurahman',location: "Abinet, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '755 ETB' },
    { id: 14, lastName: 'Hailu', firstName: 'Yohanes', fullname: 'Yohanes Hailu',location: "Atikilt tera, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '655 ETB' },
    { id: 15, lastName: 'Amare', firstName: 'Dawit', fullname: 'Dawit Amare',location: "Ayat, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '555 ETB' },
    { id: 16, lastName: 'Sisay', firstName: 'Simon', fullname: 'Simon Sisay',location: "Asko, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '455 ETB' },
    { id: 17, lastName: 'Solomon', firstName: 'Sifen', fullname: 'Sifen Solomon',location: "CMC, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '285 ETB' },
    { id: 18, lastName: 'Eyob', firstName: 'Kefyalew', fullname: 'Kefyalew Eyob',location: "Summit, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '295 ETB' },
    { id: 19, lastName: 'Dawit', firstName: 'Amare', fullname: 'Amare Dawit',location: "Shero meda, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '155 ETB' },
    { id: 20, lastName: 'Kalkidan', firstName: 'Bekele', fullname: 'Bekele Kalkidan',location: "5Kilo, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '265 ETB' },
    { id: 21, lastName: 'Abelneh', firstName: 'Samuel', fullname: 'Abelneh Samuel',location: "Stadium, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '295 ETB' },
    { id: 22, lastName: 'Kebede', firstName: 'Abebe', fullname: 'Kebede Abebe',location: "Bole, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '288 ETB' },
    { id: 23, lastName: 'Alemu', firstName: 'Alemua', fullname: 'Girma Kidus',location: "Bole, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '252 ETB' },
    { id: 24, lastName: 'Gizachew', firstName: 'Abel', fullname: 'Abel Gizachew',location: "Lideta, Addis Ababa",status: "Pending", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '455 ETB' },
    { id: 24, lastName: 'Shimeles', firstName: 'Liuel', fullname: 'Liuel Shimeles',location: "Bole, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '775 ETB' },
    { id: 25, lastName: 'Eyob', firstName: 'Samuel', fullname: 'Samuel Eyob',location: "Gofa, Addis Ababa",status: "Completed", avatar:"/images/smiley.jpg" , phoneNum: +251921567692, totalSpent: '666 ETB' },
  ];


  export const productRows = [
    {
      id: 1,
      product: "Banana",
      name: "Banana",
      category: "Fruit",
      img: "/images/banana.jpg",
      stock: "180 Kg",
      status: "Pending",
      phoneNum: "+251921567692",
      price: "40.00",
      location: "Summit, Addis Ababa"
    },
    {
      id: 2,
      name: "Potatoes",
      category: "Vegetable",
      img: "/images/potato.jpg",
      stock: "400 Kg",
      status: "active",
      price: "22.00",
    },
    {
      id: 3,
      name: "Tomatoes",
      category: "Vegetable",
      img: "/images/tomato.jpg",
      stock: "90 Kg",
      status: "active",
      price: "26.00",
    },
    {
      id: 4,
      name: "Onions",
      category: "Vegetable",
      img: "/images/onions.jpg",
      stock: "604 Kg",
      status: "active",
      price: "34.00",
    },
    {
      id: 5,
      name: "Milk",
      category: "Dairy",
      img: "/images/milk.jpg",
      stock: "80 L",
      status: "active",
      price: "29.00",
    },
    {
      id: 6,
      name: "Orange",
      category: "Fruit",
      img: "/images/orange.jpg",
      stock: "450 Kg",
      status: "active",
      price: "70.00",
    },
    {
      id: 7,
      name: "Avocado",
      category: "Fruit",
      img: "/images/avocado.jpg",
      stock: "215 Kg",
      status: "active",
      price: "30.00",
    },
    {
      id: 8,
      name: "Egg",
      category: "Dairy",
      img: "/images/Egg.jpg",
      stock: "669",
      status: "inactive",
      price: "11.50",
    },
    {
      id: 9,
      name: "Yoghurt",
      category: "Dairy",
      img: "/images/yoghurt.jpg",
      stock: "99",
      status: "active",
      price: "29.00",
    },
    {
      id: 10,
      name: "Mango",
      category: "Fruit",
      img: "/images/mango.jpg",
      stock: "213 Kg",
      status: "active",
      price: "60.00",
    },
    {
      id: 11,
      name: "Pineapple",
      category: "Fruit",
      img: "/images/pineapple.jpg",
      stock: "120",
      status: "active",
      price: "90.00",
    },
    {
      id: 12,
      name: "Avocado",
      category: "Fruit",
      img: "/images/avocado.jpg",
      stock: "215 Kg",
      status: "active",
      price: "30.00",
    },
    {
      id: 13,
      name: "Egg",
      category: "Dairy",
      img: "/images/Egg.jpg",
      stock: "669",
      status: "inactive",
      price: "11.50",
    },
    {
      id: 14,
      name: "Yoghurt",
      category: "Dairy",
      img: "/images/yoghurt.jpg",
      stock: "99",
      status: "active",
      price: "29.00",
    },
    {
      id: 15,
      name: "Mango",
      category: "Fruit",
      img: "/images/mango.jpg",
      stock: "213 Kg",
      status: "active",
      price: "60.00",
    },
  ];